// <auto-generated />
using System;
using DotnetCleanApiTemplate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotnetCleanApiTemplate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotnetCleanApiTemplate.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e57e4bc8-8a7b-4a0e-bf8e-f56d7193b94b"),
                            CreatedUtc = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Roadmap draft"
                        },
                        new
                        {
                            Id = new Guid("45ca059c-867b-4be9-b4e3-8209ec14f1ec"),
                            CreatedUtc = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Architecture notes"
                        },
                        new
                        {
                            Id = new Guid("b3f93584-8602-42ba-b6d1-7a36f9b0e9e2"),
                            CreatedUtc = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Release checklist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
